#ifndef RAYTRACINGINONEWEEKEND_UTILS_RANDOM_HPP
#define RAYTRACINGINONEWEEKEND_UTILS_RANDOM_HPP

[[nodiscard]] double random(double min, double max);

#endif //RAYTRACINGINONEWEEKEND_UTILS_RANDOM_HPP
